### ISSUE TITLE
Slow for files with size in KBs

### ISSUE THREAD

**Issue by muskanrafi44** [Ibrar-Hussain/CS311S20PID26#1]
We have tried to compress files of different size randomly. Very small size files are compressing or decompressing the way they are supposed to be. But for file with size in KB or greater they are taking a lot time. e.g. For 18 KB file it was taking around 5 minutes in total with detail is 3 minutes for files compressing or decompressing and then 2 minutes to it was browsing to show message that file has compressed.

**Comment by MinahalTayyab** [comment]
It varies in different computers. It takes 2 min and 30 sec to compress and 1 sec to decompress for 18 KB file  in my PC.

**Comment by Ibrar-Hussain** [comment]
> It varies in different computers. It takes 2 min and 30 sec to compress and 1 sec to decompress for 18 KB file in my PC.

Issue solved. Now it is working in 15 sec for 25kb file
