### ISSUE TITLE
Can be made more User Friendly (Improvement in UI)

### ISSUE THREAD

**Issue by Faria-Tanveer** [Ibrar-Hussain/CS311S20PID26#2]
There are some suggestion for improvement in UI are here:

1.  Group can use File Upload tool box with better style to show the user the text that Click here to Select file instead of just three dots as it is little confusing.
2. When at last message shows that file has compressed or decompressed it must show that path where it has store. as output files were storing at default location not at user specified location.

**Comment by MinahalTayyab** [comment]
We have provided the path where the files are saved.
