### ISSUE TITLE
Improvement in Backend 

### ISSUE THREAD

**Issue by muskanrafi44** [Ibrar-Hussain/CS311S20PID26#3]
Suggestion for improvement in backend are here:
1. While opening the application we have to click on setup for each time and it was every time installing it. There should be some way to install it once and then use it with just one click..
2. At the time saving output file ask user to give it name as file are storing at default location with default name that is very confusing if many files are stored there.
3. Same as point no 2 path should be user defined not default.

**Comment by MinahalTayyab** [comment]
It's the fault of your own machine, we checked it on 4 different computers and there was no need to install it again and again.
