### ISSUE TITLE
Issue with Algorithm

### ISSUE THREAD

**Issue by Faria-Tanveer** [Ibrar-Hussain/CS311S20PID26#4]
As App was only compressing/decompressing text files so if the text file contain some special symbols in it or mathematical symbol algorithm find it a little bit more difficult to handle along with large file so algorithm can be improve to handle symbols along with characters.
As it is a desktop application so you can use database with it to make it more easy for the user to browse his/her previously compressed files from history saved in app.

**Comment by MinahalTayyab** [comment]
We faced no issue in handling special symbols or mathematical symbols. and we don't think there is any need of database.
